<?php
/**
 * DetailedActivityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DetailedActivityTest Class Doc Comment
 *
 * @category    Class
 * @description DetailedActivity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DetailedActivityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DetailedActivity"
     */
    public function testDetailedActivity()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "photos"
     */
    public function testPropertyPhotos()
    {
    }

    /**
     * Test attribute "gear"
     */
    public function testPropertyGear()
    {
    }

    /**
     * Test attribute "calories"
     */
    public function testPropertyCalories()
    {
    }

    /**
     * Test attribute "segment_efforts"
     */
    public function testPropertySegmentEfforts()
    {
    }

    /**
     * Test attribute "device_name"
     */
    public function testPropertyDeviceName()
    {
    }

    /**
     * Test attribute "embed_token"
     */
    public function testPropertyEmbedToken()
    {
    }

    /**
     * Test attribute "splits_metric"
     */
    public function testPropertySplitsMetric()
    {
    }

    /**
     * Test attribute "splits_standard"
     */
    public function testPropertySplitsStandard()
    {
    }

    /**
     * Test attribute "laps"
     */
    public function testPropertyLaps()
    {
    }

    /**
     * Test attribute "best_efforts"
     */
    public function testPropertyBestEfforts()
    {
    }
}
